### ISSUE TITLE
Source doesnot exist

### ISSUE THREAD

**Issue by Racinghart7** [elastic/elasticsearch-river-twitter#103]
Correction in pom.xml for 2.5.0-SNAPSHOT 

UPDATE:

    <parent>
        <groupId>org.elasticsearch</groupId>
        <artifactId>elasticsearch-parent</artifactId>
        <version>1.5.1-SNAPSHOT</version>
    </parent>

CURRENT:

    <parent>
        <groupId>org.elasticsearch</groupId>
        <artifactId>elasticsearch-parent</artifactId>
        <version>1.5.0-SNAPSHOT</version>
    </parent>

VERSION 1.5.0-SNAPSHOT doesnot exist.

**Comment by dadoonet** [comment]
Will be fixed by https://github.com/elastic/elasticsearch-river-twitter/issues/101
