### ISSUE TITLE
Kibana unable to detect created_at field for Raw Twitter Stream

### ISSUE THREAD

**Issue by guptayuvraj** [elastic/elasticsearch-river-twitter#107]
Hey I am using Kibana 4.
When I am running ES-Twitter River by indexing RAW twitter stream as specifying raw:true, Kibana is not able to detect a time-stamped field from the data.
Whereas when using raw:false, Kibana is able to detect time-stamped field (Created_at).

Kindly give a possible solution to index RAW twitter stream so that Kibana detects a time-stamp field.

**Comment by dadoonet** [comment]
This plugin will end with Elasticsearch 2.0.
Please consider using logstash input Twitter
