### ISSUE TITLE
No media on twiter with images

### ISSUE THREAD

**Issue by thor27** [elastic/elasticsearch-river-twitter#77]
Hi,

I created an index with:

```js
{
  "type": "twitter",
  "twitter": {
    "follow": "2813910352,295781723",
  }
}
```

And after I posted a tweet with image there was no entities or media with image URL.

Thanks!

**Comment by crbarahona** [comment]
It doesn't look like river-twitter is making use of the MediaEntity yet, I think it could be done very similarly to the URLentity handler, though. https://github.com/elasticsearch/elasticsearch-river-twitter/blob/master/src/main/java/org/elasticsearch/river/twitter/TwitterRiver.java#L672

Twitter4j does already implement a MediaEntity interface. http://twitter4j.org/javadoc/twitter4j/MediaEntity.html

On the other hand, I think that the image url would likely show up in link[i].expand_url as implemented through the URLentity handler.

**Comment by dadoonet** [comment]
Thanks for opening this.
But we won't support new features as rivers are now [deprecated](https://www.elastic.co/blog/deprecating_rivers).

Feel free to open this feature request in Logstash if it's not already available.
