### ISSUE TITLE
retweet.id not accurate

### ISSUE THREAD

**Issue by Vineeth-Mohan** [elastic/elasticsearch-river-twitter#78]
I feel as long cant hold the value of retweet.id , its getting rounded up or something. Due to this , its showing the wrong retweet.id in ES side which cant be used for filtering nor can be used to track back  to the  original link.

**Comment by dadoonet** [comment]
Sorry for the long delay.

You could change I think the mapping before creating the river.
But sort on this field will give weird results (or you can use multifield).

Also have a look at https://github.com/MikeMcl/bignumber.js/ and see if it can help you.

**Comment by Vineeth-Mohan** [comment]
Well i brought this as a issue here because the mapping is defined in the river code. Changing there might be the most appropriate.

**Comment by dadoonet** [comment]
This project has been stopped since elasticsearch 2.0.
